title: "Is Linux About…?"
description: "Linux is a kernel. So what’s it about?"
permalink: /:title/
theme-color: "#7239b3"
gravatar: eaa3cc978770998ea2bd4382935bf0f4
twitter: CassidyJames
author: Cassidy James Blaede

collections:
  desktop-environments:
    title: Desktop Environments
    output: false

plugins:
  - jekyll-redirect-from

markdown: kramdown

future: false # Allows us to stage posts
exclude: [README.md, Gemfile, Gemfile.lock, vendor]

